In [1]:
import modin.pandas as pd

In [2]:
modin_df = pd.read_csv('Rate.csv')
modin_df

UserWarning: Ray execution environment not yet initialized. Initializing...
To remove this warning, run the following python code before doing dataframe operations:

    import ray
    ray.init()

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,FederalTIN,RateEffectiveDate,RateExpirationDate,...,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents,RowNumber
0,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,29.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
1,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,14
2,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,15
3,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
4,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12694440,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2033
12694441,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2034
12694442,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2035
12694443,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2036
12694444,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2037

In [3]:
modin_df.shape

(12694445, 24)

In [4]:
modin_df.columns

Index(['BusinessYear', 'StateCode', 'IssuerId', 'SourceName', 'VersionNum',
       'ImportDate', 'IssuerId2', 'FederalTIN', 'RateEffectiveDate',
       'RateExpirationDate', 'PlanId', 'RatingAreaId', 'Tobacco', 'Age',
       'IndividualRate', 'IndividualTobaccoRate', 'Couple',
       'PrimarySubscriberAndOneDependent', 'PrimarySubscriberAndTwoDependents',
       'PrimarySubscriberAndThreeOrMoreDependents', 'CoupleAndOneDependent',
       'CoupleAndTwoDependents', 'CoupleAndThreeOrMoreDependents',
       'RowNumber'],
      dtype='object')

In [5]:
# row*column
modin_df.size

304666680

In [6]:
import pandas
df = pandas.read_csv("Rate.csv")
df

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,FederalTIN,RateEffectiveDate,RateExpirationDate,...,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents,RowNumber
0,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,29.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
1,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,14
2,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,15
3,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
4,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12694440,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2033
12694441,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2034
12694442,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2035
12694443,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2036
12694444,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2037

Using modin gave a faster performance than pandas and has less impact on my RAM since I could hear the laptop fan making noise when I attempted with pandas alone.

In [7]:
df2 = pd.read_csv('custom_1988_2020.csv')
df2

2022-07-15 13:44:46,433	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_deploy_ray_func() (pid=29504, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 663, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 667, in ray._raylet.execute_task
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\execution\ray\common\task_wrapper.py", line 42, in _deploy_ray_func
    return func(**args)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 298, in parse
    return PandasParser.generic_parse(fname, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 197, in generic_parse
    pandas_df = callback(BytesIO(to_read), **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\io\text\csv_dispatcher.py", line 40, in read_callback
    return pandas.read_csv(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
    return parser.read(nrows)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1270, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 156, in arrays_to_mgr
    return create_block_manager_from_column_arrays(
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1954, in create_block_manager_from_column_arrays
    blocks = _form_blocks(arrays, consolidate)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2028, in _form_blocks
    values, placement = _stack_arrays(list(tup_block), dtype)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2067, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 865. MiB for an array with shape (8, 14174062) and data type int64
2022-07-15 13:44:46,511	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::_deploy_ray_func() (pid=29504, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 663, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 667, in ray._raylet.execute_task
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\execution\ray\common\task_wrapper.py", line 42, in _deploy_ray_func
    return func(**args)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 298, in parse
    return PandasParser.generic_parse(fname, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 197, in generic_parse
    pandas_df = callback(BytesIO(to_read), **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\io\text\csv_dispatcher.py", line 40, in read_callback
    return pandas.read_csv(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
    return parser.read(nrows)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1270, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 156, in arrays_to_mgr
    return create_block_manager_from_column_arrays(
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1954, in create_block_manager_from_column_arrays
    blocks = _form_blocks(arrays, consolidate)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2028, in _form_blocks
    values, placement = _stack_arrays(list(tup_block), dtype)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2067, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 865. MiB for an array with shape (8, 14174062) and data type int64

RayTaskError(MemoryError): ray::_deploy_ray_func() (pid=29504, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 663, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 667, in ray._raylet.execute_task
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\execution\ray\common\task_wrapper.py", line 42, in _deploy_ray_func
    return func(**args)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 298, in parse
    return PandasParser.generic_parse(fname, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 197, in generic_parse
    pandas_df = callback(BytesIO(to_read), **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\modin\core\io\text\csv_dispatcher.py", line 40, in read_callback
    return pandas.read_csv(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
    return parser.read(nrows)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1270, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\construction.py", line 156, in arrays_to_mgr
    return create_block_manager_from_column_arrays(
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 1954, in create_block_manager_from_column_arrays
    blocks = _form_blocks(arrays, consolidate)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2028, in _form_blocks
    values, placement = _stack_arrays(list(tup_block), dtype)
  File "C:\Users\kojoa\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 2067, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 865. MiB for an array with shape (8, 14174062) and data type int64

Using Modin could not allow read of this file.

By default, dask does not store data in RAM.

In [8]:
from dask.distributed import Client
client = Client(n_workers= 1, threads_per_worker= 4, processes= True, memory_limit= '2GB')
client

In [9]:
import dask.dataframe as dd
df3 = dd.read_csv("custom_1988_2020.csv")
df3

Dask DataFrame Structure:
               198801      1    103    100 000000190      0  35843  34353
npartitions=71
                int64  int64  int64  int64     int64  int64  int64  int64
                  ...    ...    ...    ...       ...    ...    ...    ...
...               ...    ...    ...    ...       ...    ...    ...    ...
                  ...    ...    ...    ...       ...    ...    ...    ...
                  ...    ...    ...    ...       ...    ...    ...    ...
Dask Name: read-csv, 71 tasks

In [10]:
df3.head()

   198801  1  103  100  000000190  0  35843  34353
0  198801  1  103  100  120991000  0   1590   4154
1  198801  1  103  100  210390900  0   4500   2565
2  198801  1  103  100  220890200  0   3000    757
3  198801  1  103  100  240220000  0  26000  40668
4  198801  1  103  100  250410000  0      5   8070

In [11]:
df3.shape

(Delayed('int-667fc06c-3191-4363-b512-bd8eeefda5d2'), 8)

Data reading was really fast with dask.

In [12]:
df_new = dd.read_csv("02-20-2018.csv", assume_missing= True)
df_new

Dask DataFrame Structure:
               Flow ID  Src IP Src Port  Dst IP Dst Port Protocol Timestamp Flow Duration Tot Fwd Pkts Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd Pkt Len Max Fwd Pkt Len Min Fwd Pkt Len Mean Fwd Pkt Len Std Bwd Pkt Len Max Bwd Pkt Len Min Bwd Pkt Len Mean Bwd Pkt Len Std Flow Byts/s Flow Pkts/s Flow IAT Mean Flow IAT Std Flow IAT Max Flow IAT Min Fwd IAT Tot Fwd IAT Mean Fwd IAT Std Fwd IAT Max Fwd IAT Min Bwd IAT Tot Bwd IAT Mean Bwd IAT Std Bwd IAT Max Bwd IAT Min Fwd PSH Flags Bwd PSH Flags Fwd URG Flags Bwd URG Flags Fwd Header Len Bwd Header Len Fwd Pkts/s Bwd Pkts/s Pkt Len Min Pkt Len Max Pkt Len Mean Pkt Len Std Pkt Len Var FIN Flag Cnt SYN Flag Cnt RST Flag Cnt PSH Flag Cnt ACK Flag Cnt URG Flag Cnt CWE Flag Count ECE Flag Cnt Down/Up Ratio Pkt Size Avg Fwd Seg Size Avg Bwd Seg Size Avg Fwd Byts/b Avg Fwd Pkts/b Avg Fwd Blk Rate Avg Bwd Byts/b Avg Bwd Pkts/b Avg Bwd Blk Rate Avg Subflow Fwd Pkts Subflow Fwd Byts Subflow Bwd Pkts Subflow Bwd Byts Init Fwd Win Byts Init Bwd Win Byts Fwd Act Data Pkts Fwd Seg Size Min Active Mean Active Std Active Max Active Min Idle Mean Idle Std Idle Max Idle Min   Label
npartitions=63
                object  object  float64  object  float64  float64    object       float64      float64      float64         float64         float64         float64         float64          float64         float64         float64         float64          float64         float64     float64     float64       float64      float64      float64      float64     float64      float64     float64     float64     float64     float64      float64     float64     float64     float64       float64       float64       float64       float64        float64        float64    float64    float64     float64     float64      float64     float64     float64      float64      float64      float64      float64      float64      float64        float64      float64       float64      float64          float64          float64        float64        float64          float64        float64        float64          float64          float64          float64          float64          float64           float64           float64           float64          float64     float64    float64    float64    float64   float64  float64  float64  float64  object
                   ...     ...      ...     ...      ...      ...       ...           ...          ...          ...             ...             ...             ...             ...              ...             ...             ...             ...              ...             ...         ...         ...           ...          ...          ...          ...         ...          ...         ...         ...         ...         ...          ...         ...         ...         ...           ...           ...           ...           ...            ...            ...        ...        ...         ...         ...          ...         ...         ...          ...          ...          ...          ...          ...          ...            ...          ...           ...          ...              ...              ...            ...            ...              ...            ...            ...              ...              ...              ...              ...              ...               ...               ...               ...              ...         ...        ...        ...        ...       ...      ...      ...      ...     ...
...                ...     ...      ...     ...      ...      ...       ...           ...          ...          ...             ...             ...             ...             ...              ...             ...             ...             ...              ...             ...         ...         ...           ...          ...          ...          ...         ...          ...         ...         ...         ...         ...          ...         ...         ...         ...           ...           ...           ...           ...            ...            ...        ...        ...         ...         ...          ...         ...         ...          ...          ...          ...          ...          ...          ...            ...          ...           ...          ...              ...              ...            ...            ...              ...            ...            ...              ...              ...              ...              ...              ...               ...               ...               ...              ...         ...        ...        ...        ...       ...      ...      ...      ...     ...
                   ...     ...      ...     ...      ...      ...       ...           ...          ...          ...             ...             ...             ...             ...              ...             ...             ...             ...              ...             ...         ...         ...           ...          ...          ...          ...         ...          ...         ...         ...         ...         ...          ...         ...         ...         ...           ...           ...           ...           ...            ...            ...        ...        ...         ...         ...          ...         ...         ...          ...          ...          ...          ...          ...          ...            ...          ...           ...          ...              ...              ...            ...            ...              ...            ...            ...              ...              ...              ...              ...              ...               ...               ...               ...              ...         ...        ...        ...        ...       ...      ...      ...      ...     ...
                   ...     ...      ...     ...      ...      ...       ...           ...          ...          ...             ...             ...             ...             ...              ...             ...             ...             ...              ...             ...         ...         ...           ...          ...          ...          ...         ...          ...         ...         ...         ...         ...          ...         ...         ...         ...           ...           ...           ...           ...            ...            ...        ...        ...         ...         ...          ...         ...         ...          ...          ...          ...          ...          ...          ...            ...          ...           ...          ...              ...              ...            ...            ...              ...            ...            ...              ...              ...              ...              ...              ...               ...               ...               ...              ...         ...        ...        ...        ...       ...      ...      ...      ...     ...
Dask Name: read-csv, 63 tasks

In [13]:
df_new.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,172.31.69.25-94.231.103.172-22-45498-6,94.231.103.172,45498.0,172.31.69.25,22.0,6.0,20/02/2018 08:34:07,888751.0,11.0,11.0,...,32.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign
1,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0.0,8.0.6.4,0.0,0.0,20/02/2018 08:33:22,112642816.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,7.071068,56300000.0,56300000.0,Benign
2,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0.0,8.0.6.4,0.0,0.0,20/02/2018 08:36:11,112642712.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,18.384776,56300000.0,56300000.0,Benign
3,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0.0,8.0.6.4,0.0,0.0,20/02/2018 08:39:00,112642648.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,5.656854,56300000.0,56300000.0,Benign
4,8.0.6.4-8.6.0.1-0-0-0,8.6.0.1,0.0,8.0.6.4,0.0,0.0,20/02/2018 08:41:49,112642702.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,65.053824,56300000.0,56300000.0,Benign

In [14]:
df_new.shape

(Delayed('int-b3114d9a-ee35-4fc4-848b-654ed8068582'), 84)

In [15]:
pd.read_csv?